name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go-version: [ '1.19', '1.20', '1.21.x' ]


    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    #   - name: Setup Go ${{ matrix.go-version }}
    #     uses: actions/setup-go@v5
    #     with:
    #       go-version: ${{ matrix.go-version }}


#    - name: Install dependencies
        # run: |
        #   go get .
        #   go get example.com/octo-examplemodule
        #   go get example.com/octo-examplemodule@v1.3.4

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
